version: '3'

services:
   web:
       build: .
       volumes:
           - .:/code
       ports:
           - "8000:8000"
       depends_on:
           - db
       command: python manage.py runserver 0.0.0.0:8000
   db:
       image: postgres
       ports: 
           - "5432"
       environment:
         - POSTGRES_DB=postgres
         - POSTGRES_USER=postgres
         - POSTGRES_PASSWORD=postgres